GET http://localhost:3000/books


###
#get by id
GET http://localhost:3000/books/1

### post books
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
  "name": "the valley",
  "author_id": 1
}

### post books check validation
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
  "name": "dooms day",
  "author_id": 20
}


### post authors
POST http://localhost:3000/authors HTTP/1.1
content-type: application/json

{
  "name": "John Smith"
}
